spring.application.name=route-optimizer-backend
server.port=8080

# External API
job.api.url=https://service-connect.free.beeceptor.com/tickets

# Sunquick Lanka Pvt Ltd coordinates (starting point)
start.location.lat=7.2906
start.location.lng=79.8653
start.location.name=Sunquick Lanka Pvt Ltd

# CORS
cors.allowed.origin=http://localhost:5173